# Generated by Django 3.2.8 on 2021-10-26 06:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211018_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='face-recognition.png', storage=main.models.OverwriteStorage(), upload_to='profile', verbose_name='이미지'),
        ),
    ]
