# Generated by Django 3.2.8 on 2021-11-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=None, max_length=128, verbose_name='방 아이디')),
                ('room_password', models.CharField(max_length=64, verbose_name='방 비밀번호')),
                ('room_name', models.CharField(max_length=128, verbose_name='방 이름')),
                ('file', models.FileField(default='NULL', upload_to='room', verbose_name='파일')),
                ('maker', models.EmailField(default='NULL', max_length=64, verbose_name='생성자')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('member_list', models.CharField(default=None, max_length=64, verbose_name='회원명단리스트')),
            ],
            options={
                'verbose_name': 'Room 명단',
                'verbose_name_plural': 'Room 명단',
                'db_table': 'room',
            },
        ),
    ]
