# Generated by Django 3.2.8 on 2021-11-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='NULL', max_length=128, verbose_name='방 ID')),
                ('email', models.EmailField(default='NULL', max_length=128, verbose_name='사용자 email')),
                ('username', models.CharField(default='NULL', max_length=128, verbose_name='사용자 이름')),
                ('count', models.IntegerField(default=0, verbose_name='사용자 수')),
                ('rate', models.IntegerField(default=0, verbose_name='순위')),
                ('level', models.IntegerField(default=0, verbose_name='집중도 레벨')),
                ('app', models.IntegerField(default=0, verbose_name='앱 차단 점수')),
                ('person', models.IntegerField(default=0, verbose_name='자리 이탈 점수')),
                ('time', models.IntegerField(default=0, verbose_name='학습 시간')),
                ('list', models.IntegerField(default=0, verbose_name='list 변수')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '집중도',
                'verbose_name_plural': '집중도',
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='학생')),
                ('room_id', models.CharField(default=None, max_length=128, verbose_name='방 ID')),
                ('room_password', models.CharField(max_length=64, verbose_name='방 비밀번호')),
                ('room_name', models.CharField(max_length=128, verbose_name='방 이름')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
            ],
            options={
                'verbose_name': 'enrol 명단',
                'verbose_name_plural': 'enrol 명단',
                'db_table': 'enrol',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='NULL', max_length=128, verbose_name='방 ID')),
                ('writer', models.EmailField(default='NULL', max_length=128, verbose_name='작성자 email')),
                ('writername', models.CharField(default='NULL', max_length=128, verbose_name='작성자 이름')),
                ('title', models.CharField(default='NULL', max_length=128, verbose_name='제목')),
                ('description', models.CharField(default='NULL', max_length=1000, verbose_name='내용')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='질문 아이디')),
                ('maker', models.CharField(max_length=64, null=True, verbose_name='생성자')),
                ('room_id', models.CharField(default=None, max_length=128, verbose_name='방 아이디')),
                ('question', models.CharField(max_length=64, verbose_name='질문')),
                ('item1', models.CharField(max_length=128, verbose_name='질문지1')),
                ('item2', models.CharField(max_length=128, verbose_name='질문지2')),
                ('item3', models.CharField(max_length=128, verbose_name='질문지3')),
                ('item4', models.CharField(max_length=128, verbose_name='질문지4')),
                ('answer', models.IntegerField(default=None, verbose_name='정답')),
            ],
            options={
                'verbose_name': 'Quiz 명단',
                'verbose_name_plural': 'Quiz 명단',
                'db_table': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=None, max_length=128, verbose_name='방 ID')),
                ('room_password', models.CharField(max_length=64, verbose_name='방 비밀번호')),
                ('room_name', models.CharField(max_length=128, verbose_name='방 이름')),
                ('file', models.FileField(default='NULL', upload_to='room', verbose_name='파일')),
                ('maker', models.EmailField(default='NULL', max_length=64, verbose_name='생성자')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('member_list', models.CharField(default=None, max_length=64, verbose_name='회원명단리스트')),
            ],
            options={
                'verbose_name': 'Room 명단',
                'verbose_name_plural': 'Room 명단',
                'db_table': 'room',
            },
        ),
    ]
