# Generated by Django 3.2.8 on 2021-11-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedquiz',
            name='makername',
            field=models.CharField(default='NULL', max_length=128, verbose_name='생성자 이름'),
        ),
    ]
