# Generated by Django 3.2.8 on 2021-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=None, max_length=128, verbose_name='방 아이디'),
        ),
    ]
