# Generated by Django 3.2.8 on 2021-11-16 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211116_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='make_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 날짜'),
            preserve_default=False,
        ),
    ]
