# Generated by Django 3.2.8 on 2021-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='NULL', max_length=128, verbose_name='방 이름')),
                ('email', models.EmailField(default='NULL', max_length=128, verbose_name='사용자')),
                ('count', models.IntegerField(default=0, verbose_name='사용자 수')),
                ('rate', models.IntegerField(default=0, verbose_name='순위')),
                ('level', models.IntegerField(default=0, verbose_name='집중도 레벨')),
                ('app', models.IntegerField(default=0, verbose_name='앱 차단 점수')),
                ('person', models.IntegerField(default=0, verbose_name='자리 이탈 점수')),
                ('time', models.IntegerField(default=0, verbose_name='학습 시간')),
                ('list', models.IntegerField(default=0, verbose_name='list 변수')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '집중도',
                'verbose_name_plural': '집중도',
                'db_table': 'analytics',
            },
        ),
    ]
