# Generated by Django 3.2.8 on 2021-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quiz_make_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='makername',
            field=models.CharField(default='NULL', max_length=128, verbose_name='생성자 이름'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maker',
            field=models.EmailField(max_length=64, null=True, verbose_name='생성자 이메일'),
        ),
    ]
