# Generated by Django 3.2.8 on 2021-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='username',
            field=models.CharField(default='NULL', max_length=128, verbose_name='사용자 이름'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='email',
            field=models.EmailField(default='NULL', max_length=128, verbose_name='사용자 email'),
        ),
    ]
