# Generated by Django 3.2.8 on 2021-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='room_id',
            field=models.CharField(default=None, max_length=128, verbose_name='방 아이디'),
        ),
    ]
