# Generated by Django 2.2.14 on 2021-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='maker',
            field=models.CharField(default=None, max_length=64, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
