# Generated by Django 2.2.14 on 2021-11-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211114_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='maker',
        ),
    ]
