# Generated by Django 2.2.14 on 2021-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_quiz_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='maker',
            field=models.CharField(max_length=64, null=True, verbose_name='생성자'),
        ),
    ]
