# Generated by Django 3.2.8 on 2021-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=128, verbose_name='수업 이름')),
                ('class_password', models.CharField(max_length=64, verbose_name='수업 비밀번호')),
                ('teacher', models.EmailField(default='NULL', max_length=64, verbose_name='교사')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('student_list', models.CharField(default=None, max_length=64, verbose_name='학생명단리스트')),
            ],
            options={
                'verbose_name': 'class 명단',
                'verbose_name_plural': 'class 명단',
                'db_table': 'class',
            },
        ),
    ]
